### ISSUE TITLE
semicolon in string

### ISSUE THREAD

**Issue by coderofsalvation** [HaxeFoundation/hscript#100]
I'm having an exception when doing `lines[x] = lines[x]+";";`

Any workaround for this?

I've noticed `"f".code` to get the asciival, but didn't find a libraryless way to convert charcode 59 into ';'.

**Comment by ncannasse** [comment]
what's the exception ? are you sure lines is not null ? is it at runtime or at parsing ? I'm quite sure ";" is handled correctly in parsing.

**Comment by coderofsalvation** [comment]
Hi, thanks for your reply (and amazing work on haxe so far).

The error is `App.hx:17: characters 22-23 : Expected }`

It happens here when uncommented: [App.hx](https://github.com/coderofsalvation/hscript-examples/blob/master/App.hx#L17)

background: I was curious if I could simply add semicolons, since I'm very used to languages which don't require them. Forgetting end-of-line-semicolons keeps biting me, so this issue functions as a feature request for optional hscript semicolons too ;)

**Comment by ncannasse** [comment]
Oh, I think it comes from HScript not handling regular expression syntax. The first line should be ok, the error is about 
```
lines[x] = ~/;;/;/g;
```

**Comment by coderofsalvation** [comment]
hm maybe they are somehow related, because if I remove the regex, then it'll throw:

```
/home/leon/apps/haxe/lib/hscript/2,4,0/hscript/Interp.hx:258: lines 258-269 : Uncaught exception hscript:1: Unexpected token: ";"
/home/leon/apps/haxe/lib/hscript/2,4,0/hscript/Interp.hx:254: characters 10-26 : Called from here
App.hx:24: characters 10-33 : Called from here
App.hx:29: characters 10-21 : Called from here
```
Basically for line 16<br>
Once I comment line 16, all works fine.

**Comment by ncannasse** [comment]
The following script parses correctly:

```
			var lines = [1,2,3];
			for( x in 0...3 )
				lines[x] = lines[x]+";";
			lines.join("");
```

You can only have `;` at the end of an expression within a block.
