### ISSUE TITLE
Authorize char 36 "$"

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/hscript#103]
Hej,

I'm playing with hscript on compile-time so I have a template system as tink_template using `hscript.Macro( pos ).convert( ast )`
But, on server side, I also use record-macros in templates that plays with "$" char i.e (`Tag.manager.search( $target == "Company" )`)
So I have to add "$" char to this list : https://github.com/HaxeFoundation/hscript/blob/36eb0fca8b4ad0836c7b787f65833331746feb11/hscript/Parser.hx#L116

BTW, hscript and https://github.com/filt3rek/hscript-template give a similar template system to tink_template both on run-time and compile-time.

**Comment by ncannasse** [comment]
You can modify Parser.identChars before parsing, I don't want to add $ as a default.

**Comment by filt3rek** [comment]
Hi Nicolas,
Thanks for your answer. I didn't know that. It makes sense.
