### ISSUE TITLE
Haxe 4.2.2 - Std.is is deprecated. Use Std.isOfType instead

### ISSUE THREAD

**Issue by Lbones-ai** [HaxeFoundation/hscript#105]
Hi, since I updated to Haxe 4.2.2 I'm getting this warning from hscript lib:

:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.

**Comment by Gama11** [comment]
This should already be fixed, but I guess there wasn't a new release yet: #101

**Comment by Lbones-ai** [comment]
yes I tried to update the library a few hours ago and there was no new release, thanks again!

**Comment by Gama11** [comment]
Might want to keep this open until a new release has been made.

**Comment by intoxopox** [comment]
It's been over a year. When is the next release?

**Comment by ncannasse** [comment]
I've just released HScript 2.5.0
