### ISSUE TITLE
 Invalid access to field 

### ISSUE THREAD

**Issue by MagnusStrom** [HaxeFoundation/hscript#106]
So, I have a script which haxe reads and hscript intreprets. I want all variables of playstate to be read, so I made a variable at the top of playstate:
`public static var instance:PlayState;`

And gave the variable `game`
`interp.variables.set("game", PlayState.instance); `

But, when I run it, I get the error: 
```hscript:10: Invalid access to field strumLineNotes
Error : hscript:10: Invalid access to field strumLineNotes
```

How would this b fixed?

**Comment by Simn** [comment]
Something is `null` that shouldn't be. This isn't a hscript issue but something in your own logic. Make sure all your fields are initialized properly.
