### ISSUE TITLE
Throwing SReturn 

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/hscript#113]
Hej,

Sorry again.
I can't really understand this case in Interp.hx (in expr() function): https://github.com/HaxeFoundation/hscript/blob/891a085f2b75acbf4700cfdffa80fb0b9532d325/hscript/Interp.hx#L403-L405

When I do "inclusions", in order to "share" variables between "executions", I use `expr()` function instead of `execute()`, because `execute()` resets locals...

But all my inclusions do a `return` at the end and Interp complains and throws `SReturn`.

The good thing is that just before throwing this, it fill the `retrunValue` var anyway, so I catch this, and return the returnValue (using @:privateAccess because it's private...)

Is it a normal behaviour please ?
If so, am I doing well or maybe there is another workaround ?
If there is no workaround, maybe it would be cool to throw a `hscript.Expr.ErrorDef` in this case or something more pretty than a native haxe's exception even `SReturn` is private so it's not pretty to catch this and also maybe let `returnValue` public or something like that ?

I'm sorry to "flood" github issues with my "questions/experiments" but it's not easy to ask someone about this lib elsewhere.
I thank you for your patience.

Regards,

**Comment by ncannasse** [comment]
Yes it's normal, we're using throw in order to make sure we unwind the stack for recursive expr().
You can call exprReturn() instead of expr().

**Comment by filt3rek** [comment]
Thanks Nicolas for your quick reply !
I haven't seen `exprReturn()` before, I'll use it.
BTW, maybe we could make this fonction public instead of private as it is now ?
