### ISSUE TITLE
Possible to call hScript functions from within Haxe?

### ISSUE THREAD

**Issue by robertshady** [HaxeFoundation/hscript#12]
Ok, ideally I would be able to write some hScript code like:

```
var hScript:String = "

function moveLeft()
{
    // Handle player moving left
}

function moveRight()
{
    // Handle player moving right
}
";
```

And then from within my Haxe be able to call

```
    hscript.interp().moveLeft();
```

I can't seem to figure out how to make it work.  It would be SUPER useful instead of having to write a separate script for each function...

**Comment by ADA-Funni** [comment]
> First interp.your program, then get the function with interp.variables.get("moveLeft"), which you can then call anytime.

I know this comment is old, but I was trying to figure out how to do this and thought I might as well share how I did this in my project.

<img width="882" height="286" alt="Image" src="https://github.com/user-attachments/assets/1409d150-206c-4aed-9ebe-95fb2e9bc51a" />
