### ISSUE TITLE
Type's path

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/hscript#122]
Hej,

Idk if it's the right behaviour but in Haxe when I switch against `Type.typeof` , the case statements expect `Type.ValueType.TNull` for example whereas in hscript I get "Invalid access to field TNull" and I have to write `case Type.TNull : ` instead.

Thx for reading me,
Regards

**Comment by ncannasse** [comment]
Because hscript is dynamically typed, you need to be explicit about the
values you're matching or import them as part of the global scope (in
variables)

Le mer. 19 juil. 2023 à 18:49, M.Romecki ***@***.***> a
écrit :

**Comment by filt3rek** [comment]
Thx Nicolas for your answer.
I understand that I have to be explicit, but here I was excplicit telling hscript `Type.ValueType.TNull` (not only `TNull`), but it throws me "Invalid access to field TNull". To make it working I have to write `Type.TNull` and this is what I find weird.
But maybe I misunderstood something.

**Comment by ncannasse** [comment]
It should be ValueType.TNull and ValueType should be set as a global
variable

Le mer. 19 juil. 2023 à 20:37, M.Romecki ***@***.***> a
écrit :

**Comment by filt3rek** [comment]
I should have been more clear at the begining : I've already imported "Type" in global scope like that : `interp.variables.set( "Type", Type );`
And then having `case Type.ValueType.TNull` gives me "Invalid access to field TNull" whereas with `case Type.TNull` it works fine. Like if TNull was on Type and not on Type.ValueType...
I'm sure that if I import ValueType directly in global scope it would work fine but here I just find strange that it finds TNull on Type and not on Type.ValueType :)

**Comment by ncannasse** [comment]
Type.ValueType will give null. It won't work. Same as Type.TNull

Le mer. 19 juil. 2023 à 20:51, M.Romecki ***@***.***> a
écrit :

**Comment by filt3rek** [comment]
My bad, you're right.
My confusion comes from that I've done my tests on PHP target which gives sometimes weird values when playing with Dynamic.
Sorry for the disturbance guys, have nice evening ;)
