### ISSUE TITLE
Easy way to add checker types 

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/hscript#124]
Is there an easy way to add a type to the checkerTypes without generating the XML? 

I'm using hscript inside a hashlink program and want to add a few types to the checker, but don't want to manually build the descriptions.  Is there an easy way to add the  types? ideally at compile time?

Would it be possible to use a macro to do it?

**Comment by onehundredfeet** [comment]
This is what I have:

    ```haxe
    static function addRttiTypes( checkerTypes: CheckerTypes, rttiTypes : Array<TypeTree> ) {
		var todo = [];
		for( v in rttiTypes ) {
			@:privateAccess checkerTypes.addXmlType(v,todo);
        }
		for( f in todo )
			f();
	}
    addRttiTypes(types, exposedTypes.map((x) -> TClassdecl(haxe.rtti.Rtti.getRtti(x))));
    ```
    But ideally, I'd like to do it without rtti.

**Comment by ncannasse** [comment]
It could be possible to write macros that generates hscript type
definitions but it's not done atm since we often use hscript type checking
in Hide anyway.

Le sam. 13 avr. 2024 à 04:59, Ryan Cleven ***@***.***> a
écrit :

**Comment by onehundredfeet** [comment]
thanks.  I've managed to work around it.
