### ISSUE TITLE
Diffrent approach for async

### ISSUE THREAD

**Issue by neimanpinchas** [HaxeFoundation/hscript#128]
Maybe a small change to the interp to add the yield keyword thus enabling some kind of cooperative multitasking.

Add a global scheduler to the interp = map with task id ,list of expr, and parent thread id
add a taskid param to the expr function, with a closure function that will cause the scheduler to resume execution of a task
Change the Eblock case from a for loop, to code that simply pushes the expr list to the scheduler
the scheduler will on a timer loop around all non yielded tasks, 
loop and execute all exprs, 
if 1 expr is a block it will yield the parent block, set the parent id on the new task
every time a task is finished, the parent task is looked up and resumed
if a expr is the yield keywork than that task is yielded the block should pass resume callback before by its own to an async function
we need to add a special case that if a block is not independent (part of TVar or passed as param, it should work sync as usual
or we need to update all blockconsumers tvar/functioncall if condition, to asyncronosly resolve all blocks before executing

**Comment by Simn** [comment]
This is out-of-scope for hscript and not a "small change".
