### ISSUE TITLE
For loops broken

### ISSUE THREAD

**Issue by NicoM1** [HaxeFoundation/hscript#13]
for loops appear to be broken currently: running 		
```
for (i in 0...10)
{
    trace("hey");
}
```

gives me: `EInvalidIterator({ max => 10, min => 0 })`

looping through a haxeflixel `FlxTypedGroup` didnt work either (that was initially what I wanted to do)

Thanks,
Nico

**Comment by icek** [comment]
You should add --macro keep('IntIterator') to extraParams.hxml.

**Comment by Simn** [comment]
That's actually a very good idea!
