### ISSUE TITLE
Suggestion: Implement anonymous object inheritance

### ISSUE THREAD

**Issue by brutalexcess** [HaxeFoundation/hscript#27]
Take the following example:

    Settings         = {};
    Settings.Message = "Hello.";
    Settings.GetMessage = function()
    {
        trace(Settings.Message);
    }

The anonymous object `Settings` contains the field `Message`, and the only way to get that data is to write the full path. In some circumstances, this may be okay, and using variables such as `var msg = Settings.Message;` is the only way to shorten it if needed to use more than once without tedious copying and pasting.

What I would like is some kind of anonymous object inheritance, using the `this` keyword or whether implied through parent-child structure like in the above example.

So instead of writing Settings.Message in a function to get the Message from the parent object, the parent is inherited into its children, so using `this` to refer to the path going to the child, or omitting entirely like so:

    Path.To.Child = function () { //assuming the Haxe Type/Reflect API is exposed
        trace(getPath(Child)) //Outputs: Path.To
        trace(getFullPath(Child)) //Outputs: Path.To.Child
        //or using `this.Child` refers to `Path.To.Child`
    }

I am no expert in the field of interpreters or parsers, so maybe this can be accomplished? Feedback appreciated.

**Comment by ncannasse** [comment]
You can already use "this" in such cases, which is the object on which the method was called.
