### ISSUE TITLE
"var" behavior for multiple execute 

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/hscript#28]
"var" making variable local for single execute. Is it bug or expected behavior? 
<pre>
	var parser = new hscript.Parser();
	var interp = new hscript.Interp();

        //version 1 broken
        interp.execute(parser.parseString("var a='qqq';")); 
        interp.execute(parser.parseString("trace(a);")); 

        //version 2 works
        interp.execute(parser.parseString("a='qqq';")); 
        interp.execute(parser.parseString("trace(a);")); 
</pre>

**Comment by ncannasse** [comment]
yes that's normal, because execute will reset the local vars, and global vars must not be declared with "var"

**Comment by codeservice** [comment]
Little bit confusing

Below code works and "a" still exists for second execute with function from first execute:
interp.execute(parser.parseString("var a='qqq';function qqq() {trace(a);}")); 
interp.execute(parser.parseString("qqq();")); 

Logical behavior if "var a" cleared only when declared inside block "{var a = "qqq";}" and execute method not exactly block.

Any way thanks for clarification!

**Comment by ncannasse** [comment]
It's possible that the parser returns EBlock(EVar("a")) for "var a='qqq';", given that a program is a single expr and not an Array of Expr

**Comment by codeservice** [comment]
Yes, only in my case I have many scripts with necessity to use it as array of Expr. Would be great if hscript can continuously process code at any moment of time. For example when you don't have whole script string initially and new script strings can be generated over time. For me not using "var" declaration works as a solution for such task.

**Comment by ncannasse** [comment]
By overriding hscript and allowing to access Interp.expr() directly this should work

**Comment by codeservice** [comment]
Unfortunately Interp.expr() always clearing EBlock "var" variables and this behavior logical.

In interp.expr EBlock I can see restore(old) method. Here "var" get killed.
I can create new EOpenBlock type and don't use restore(old) here.
And in parser update function parse( s : haxe.io.Input<b>, continuous: Bool = false</b>)  {
....
<b>if(continuous)
return if( a.length == 1 ) a[0] else mk(EOpenBlock(a),0);
else</b>
return if( a.length == 1 ) a[0] else mk(EBlock(a),0);
}
Problem it will be my local only changes, not sure if we need something like this for official hscript


interp.expr code:
                .....
		case EBlock(exprs):
			var old = declared.length;
			var v = null;
			for( e in exprs )
				v = expr(e);
			restore(old);// here all local variables cleared
			return v;
