### ISSUE TITLE
Suggestion: Allow, but ignore class declarations when allowTypes is set

### ISSUE THREAD

**Issue by DjPale** [HaxeFoundation/hscript#30]
By also allowing `class` declarations in parsing, but discarding them it is possible to make a valid file for the Haxe completion server. In this way, IDE's could be much more helpful if programming hscript.

I could make a pull request if this is interesting.

**Comment by ncannasse** [comment]
Not that much easy : there's also package, import, typedef, enum, abstract, etc etc. @Simn already has a Haxe parser in Haxe for IDE support there https://github.com/Simn/haxeparser

**Comment by NicoM1** [comment]
I did something like this for IceEntity, just stripped stuff so ides
recognized it, ugly and hackey but it worked,

Nico
