### ISSUE TITLE
support "for" with const iterator ?

### ISSUE THREAD

**Issue by joelam789** [HaxeFoundation/hscript#31]
try to exec below script but get exception 
"Error #1069: Property hasNext not found on IntIterator and there is no default value."

here is the script i run:
var t = 0; for(x in 1...10) t += x; t

**Comment by Simn** [comment]
That looks like #13, can you try with the git version of hscript?

**Comment by joelam789** [comment]
Yup, I tried with the git version.
After read issue #13 , i added   [ haxeflag name="--macro keep('IntIterator')" ]   to project.xml
And then it works!
Thank you for your quick reply ~

**Comment by waneck** [comment]
Maybe it'd make sense for us to force keeping the IntIterator elements on hscript?

**Comment by ncannasse** [comment]
I have extraParams `--macro keep('IntIterator')` but if there's another way I'm fine with it too

**Comment by mockey** [comment]
I just ran into this issue using erazor. extraParams are probably ignored, when the lib is used by another lib? What about adding `#if hscript @:keep #end` to `IntIterator`?

**Comment by ncannasse** [comment]
@mockey that's not the case, haxelib path erazor correctly adds the keep for me.

**Comment by mockey** [comment]
@ncannasse
Oh, can it be that extraParams.hxml is missing in the haxelib version (2.0.5)?
http://lib.haxe.org/p/hscript/2.0.5/files/release/
I added it manually to my installation and now it works.
Good to know that this can be seen with `haxelib path`  BTW.

**Comment by ncannasse** [comment]
Ah, right I'll make sure it's included in next release
