### ISSUE TITLE
"catch" could not be followed by block ? 

### ISSUE THREAD

**Issue by joelam789** [HaxeFoundation/hscript#32]
seems that "catch" could not be followed by a block ( { ... } )  , 
but just one statement (single expression) allowed.

Is this a bug or limitation?

BTW, "hscript.Bytes" could not be compiled successfully with flag "-D hscriptPos"

**Comment by joelam789** [comment]
seems just need to add one line to "hscript.Parser.isBlock()" to fix this issue:

case ETry(_, _, _, _): true;

Can some developer help to test and solve it ?

**Comment by ncannasse** [comment]
Thanks for reporting !

**Comment by joelam789** [comment]
So quick response, so quick fixing!
You are hardworking people!
Thank you very much!
