### ISSUE TITLE
Hscript tries to use =- as an operator and fails

### ISSUE THREAD

**Issue by TerryCavanagh** [HaxeFoundation/hscript#33]
Working on a hscript thing at the moment and noticed this weird behaviour:

``` haxe
var x=-2;
```

...causes a crash. If you space out the characters it's fine. Here's the ErrorDef:

``` haxe
Err.hx:109: ERRORHANDLE OBJECT :
,{
	e : EInvalidOp(=-), 
	pmin : 61, 
	pmax : 68
},
errorhandle.e = 
{ 
0: EInvalidOp
1: 6
2: =-
}
```

**Comment by Simn** [comment]
This is indeed a current limitation of the hscript lexer.

**Comment by increpare** [comment]
possibly ditto for, when allowtypes is set to true

var outputAr:Array<Int>=[];

getting

Unexpected ">=" in line 1:

**Comment by ncannasse** [comment]
thank you for reporting both issues !
