### ISSUE TITLE
test in test.hx throwing an EInvalidIterator  error : var a = new Array(); for( x in 0...5 ) a[x] = x; a.join('-');

### ISSUE THREAD

**Issue by increpare** [HaxeFoundation/hscript#37]
It might just be me running it incorrectly, but I'm getting a report of one of the Test.hx cases crashing (in NekoVM 2.0.0)

This one:

var a = new Array(); for( x in 0...5 ) a[x] = x; a.join('-')

I'm not sure why (when I try to test it in a live interpreter myself it seems ok). Anyway, here's the call stack:

Called from ? line 1
Called from Test.hx line 70
Called from Test.hx line 15
Called from hscript/Interp.hx line 206
Called from hscript/Interp.hx line 210
Called from hscript/Interp.hx line 211
Called from hscript/Interp.hx line 294
Called from hscript/Interp.hx line 341
Called from hscript/Interp.hx line 512
Called from hscript/Interp.hx line 505
Uncaught exception - EInvalidIterator({ max => 5, min => 0 })

**Comment by ncannasse** [comment]
That seems related to DCE, the iterator() function seems to be optimized out. Which Haxe version is used in this case ? This can be fixed by compiling with `-dce no`

**Comment by increpare** [comment]
Yep, that does it. Sorry to bother! Thanks :)
