### ISSUE TITLE
EUnexpected returning incorrect emin/max sometimes in parseString? (compiled with hscriptPos)

### ISSUE THREAD

**Issue by increpare** [HaxeFoundation/hscript#39]
SHORT VERSION

The line

    "e" a

has an error at position 4, whereas the line

    "é" a

has an error at position 5.

This means it's getting confused, right?  Shouldn't it be giving the same for both?  

(every additional é character seems to push the error further out - so '"éé" a' has an error at 7)

DETAILED VERSION

    import hscript.*;
    import hscript.Expr.Error;

    class Test {

      static function test(expr:String){
        try {
          var parser = new hscript.Parser();
          var ast = parser.parseString(expr);
        } catch ( err : Dynamic ){
          trace(err); 
        }
      }

      static function main() {
        test('"e" a');
        test('"é" a');
      }

    }

produces

    Test.hx:10: { pmax => 4, pmin => 4, e => EUnexpected(a) }
    Test.hx:10: { pmax => 5, pmin => 5, e => EUnexpected(a) }

(all compiled with -D hscriptPos)

**Comment by increpare** [comment]
ah ok, it's because you're measuring bytes, rather than characters..

**Comment by increpare** [comment]
In case anyone comes across this, this function seems to convert correctly from byte position to char position:

    private static function getCharPosition(s:String, bytePos:Int):Int {
      var bytes = haxe.io.Bytes.ofString(s);
      return bytes.getString(0,bytePos).length;
    }

**Comment by ncannasse** [comment]
Yes, we use binary position, like the Haxe compiler does.
