### ISSUE TITLE
IntIterator is stripped by dce std, leaving for loops over constants failing

### ISSUE THREAD

**Issue by Mechameesh** [HaxeFoundation/hscript#43]
If you run a script containing a for loop iterating between two int constants
e.g.
````
for(i in 0 ... 10) 
{
    //some more code
}
````
and compiling without setting -dce no then the [IntIterator](http://api.haxe.org/IntIterator.html) class from the haxe Stdlib is stripped of  the `hasNext` and `next` functions (unless of course, you have explicitly used IntIterator in your code).
This in turn makes the `makeIterator`function in [Interp](https://github.com/HaxeFoundation/hscript/blob/master/hscript/Interp.hx) fail (on line 506 as of writing).

A quick fix is to set `--macro keep("IntIterator")` as a parameter to the haxe compiler, but I'm assuming that there is probably a more elegant way to handle this. This might or might not be hscripts "responsibility", but I thought it worth mentioning in the README at least.

Tested using haxe 3.2.1

**Comment by Simn** [comment]
This should have been fixed by https://github.com/HaxeFoundation/hscript/commit/54c9f507b8bdf67fb1989768394ca767b11c2604. I'm not sure if there has been a haxelib release since then.

**Comment by Mechameesh** [comment]
by checking the commit history, 2.0.5 was released on haxelib after that commit, but that the release.bat file did not properly copy the extraParams.hxml file over (possibly the release was done manually)

**Comment by Mechameesh** [comment]
Oh, and sorry for not checking the issue history / commit history. My bad...

**Comment by ncannasse** [comment]
Yes it's right, the next version will include the extraParams.
