### ISSUE TITLE
Tests try to use haxe git with hxcpp haxelib

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/hscript#44]
which doesn't work.

**Comment by andyli** [comment]
Fixed in https://github.com/HaxeFoundation/hscript/commit/7b374655da1ffd82cf87c917eadbeea683dcce43

**Comment by Simn** [comment]
That was quick, thanks!

**Comment by andyli** [comment]
That's in the easy to figure out and easy to address row ;)
