### ISSUE TITLE
cpp target failed on Linux with Haxe development

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/hscript#50]
Somehow the cpp target failed on Linux with Haxe development:

```
Class: Test EF
* Test::test()
ERR: exception thrown : OutsideBounds
* Test::testMap()
ERR: Test.hx:18(Test.assertScript) - expected 'Foo' but was 'null'
FAILED 2 tests, 2 failed, 0 success
The command "haxe build-cpp.hxml          && ./bin/Test" exited with 1.
```

It passed on Linux build with Haxe 3.2.1. And it also passed on Mac with Haxe development...

@hughsando Would you mind to take a look?

**Comment by ncannasse** [comment]
It seems it works now, can you confirm?

**Comment by andyli** [comment]
Both TravisCI and AppVeyor are green now.
