### ISSUE TITLE
Interpreter hangs without any error reporting.

### ISSUE THREAD

**Issue by xhi2art** [HaxeFoundation/hscript#53]
Weird behavior when adding a value to an Object (function). No error is reported, the system just hangs.

function a(i:Int){ 
    return i;
} 
// a is now `Object`
a += 1;   
// a is now `Object1`
a(1);
// hangs...

**Comment by ncannasse** [comment]
On which platform ?

**Comment by xhi2art** [comment]
Yes, forgot to mention. Was compiling to cpp with hxcpp, no additional libraries.

**Comment by xhi2art** [comment]
I wasn't sure that commenting to the issue page would send you a
notification (still new to github and all that :) , so i'm also sending you
a mail directly.

I'm attaching a minimal project (Main.hx and build.hxml) that will
reproduce the bug.
My hxcpp version is [3.3.49], if it helps somehow.
I ran it targetting js and the bug isn't there, it reports an error as
expected.

Apart from that, I really like the library so far, keep up the great work!

**Comment by xhi2art** [comment]
I'm attaching a minimal project (Main.hx and build.hxml) that will reproduce the bug. 
Compiling with haxe 3.3.0, and hxcpp 3.3.49.

[build.hxml](https://github.com/HaxeFoundation/hscript/files/614892/build.hxml.txt)
[Main.hx](https://github.com/HaxeFoundation/hscript/files/614893/Main.hx.txt)

**Comment by ncannasse** [comment]
On latest Haxe/HxCpp I'm getting a crash in normal mode and a "Null Object Reference" when compiled with -debug.

When running with HL I'm getting `Can't add function#2C0950(type:(void ())) and 1(type:i32)`

I'll report on hxcpp repo.
