### ISSUE TITLE
type declaration

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/hscript#59]
Hi. is it possible to create variable with type declaration?
Example

```
var expr = "var x:$Float = 123";   
var parser = new hscript.Parser(); 
var ast = parser.parseString(expr);
```

will return error `Uncaught exception - EUnexpected(:)`

Thanks.

**Comment by Simn** [comment]
See https://github.com/HaxeFoundation/hscript#limitations

**Comment by ncannasse** [comment]
Actually you can enable parsing of type declarations with `parser.allowTypes = true` but they will not be type checked and will be entirely ignored by the Interpreter.

**Comment by Simn** [comment]
Yes, that's what the linked paragraph says.

**Comment by r3d9u11** [comment]
Thanks for your answers,it very helpful!
