### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by b005t3r** [HaxeFoundation/hscript#60]
Is it possible to sandbox your scripts? Currently, a script has access to pretty much everything that is accessible from the context it's called - how do I constrain it? How do I make it access only the things I pass using ```variables``` property (like not let it instantiate classes imported in the calling context)?

**Comment by b005t3r** [comment]
Here's a small example which is currently possible and works:

```haxe
    public function runNewInstanceScript() {
        var script = '
            var obj = new ScriptObject("Johny");
            obj;
        ';

        var parser = new hscript.Parser();
        var program = parser.parseString(script);
        var interp = new hscript.Interp();

        trace(interp.execute(program));
    }
```

The class ```ScriptObject``` isn't imported through ```interp.variables``` but it's still accessible and can be instantiated.

Here's another example:

```haxe
    public function runScriptFromScript() {
        var script = '
            var script = "
                var sum = 0;
                for( a in angles )
                    sum += Math.cos(a);
                sum;
            ";

            var parser = new hscript.Parser();
            var program = parser.parseString(script);
            var interp = new hscript.Interp();

            interp.variables.set("Math", Math); // share the Math class
            interp.variables.set("angles", [0, 1, 2, 3]); // set the angles list

            "Inner script returned: " + interp.execute(program);
        ';

        var parser = new hscript.Parser();
        var program = parser.parseString(script);
        var interp = new hscript.Interp();

        interp.variables.set("Math", Math); // share the Math class

        trace(interp.execute(program));
    }
```

A script creates and calls another script.

**Comment by ncannasse** [comment]
You can subclass Interp and override pretty much all actions such as field accesses and calls to make sure that you validate things, for instance by prefixing "_sandBox_" to all your fields.
