### ISSUE TITLE
Needs license?

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/hscript#67]
I'm doing a due dilligence round on the various libraries I'm including, and I didn't notice a LICENSE.md/.txt in this repository.

Presumably it's meant to be under MIT license like the other haxe libraries? Looks like there's not many contributors so it should be fairly easy to sort this out?

**Comment by Gama11** [comment]
According to `haxelib.json`, it's already MIT, there's just no `LICENSE` file:

https://github.com/HaxeFoundation/hscript/blob/v2.1.0/haxelib.json#L4

**Comment by andyli** [comment]
The funny thing is that, in some files, e.g. https://github.com/HaxeFoundation/hscript/blob/master/hscript/Interp.hx
The license in the header is actually [BSD (2-Clause)](https://opensource.org/licenses/BSD-2-Clause)...

So, we really want to decide which is the right one and clean up the files.. 
Probably the copyright owner should be changed to HF too.
ping @ncannasse

**Comment by larsiusprime** [comment]
👍
