### ISSUE TITLE
Incremental execution of parsed code

### ISSUE THREAD

**Issue by NoRabbit** [HaxeFoundation/hscript#72]
Hi,

thanks a lot for such a tool. I was wondering if you had any plan in including some sort of incremental execution of the parsed code.
By incremental, I mean expression by expression and/or line by line. The idea is to let the users control the flow of the execution by pausing it and resuming it "whenever" they want. I would love to actually show users how their code is actually being executed and what's happening under the hood (variables being set, updated, functions being called, ...)

If no plan, would you have any idea of the complexity of adding this feature ? possible ways ?

Thanks a lot.

**Comment by Simn** [comment]
This is outside the scope of what we want to do with hscript. There have been several REPL implementations for Haxe, so I suggest you look at these. Try hitting https://community.haxe.org/ if you have further questions.
