### ISSUE TITLE
Failure to compile on nightly Haxe 4 

### ISSUE THREAD

**Issue by AustinEast** [HaxeFoundation/hscript#76]
When building the library, Im getting this build error:
```
/usr/local/lib/haxe/lib/hscript/git/hscript/Checker.hx:298: characters 18-19 : Unmatched patterns: CTNamed | CTOpt
```

I'm not sure if Haxe 4 will retain the requirement to match every pattern for a switch statement, but for now it causes this library to not compile.

**Comment by ncannasse** [comment]
It's been fixed on GIT version, I will make a new haxelib release

**Comment by ncannasse** [comment]
Done (2.3.0)
