### ISSUE TITLE
[suggestion] Making hscript modular?

### ISSUE THREAD

**Issue by darmie** [HaxeFoundation/hscript#77]
I wanted to be able to import other hscript files in a current working hscript code. I came up with this [hxComposer](https://github.com/darmie/hxComposer) :  

```hx
// module2.hscript

var Math = {
    minus : function(x, y){
        return x - y;
    }
}
exports.set("Math", Math);
```

```hx
// module.hscript
import("module2", ["Math"]); // import 'Math' from 'module2'

extend("MyModule", {
    sum : function(x , y){
        return x+y;
    }
}, Math);

exports.set("MyModule", MyModule);
```

```hx
// main.hscript
import("module", ["MyModule"]);  import 'MyModule' from 'module'

log(MyModule.minus(5, 8));
```
Whenever you import an object from a module, it is automatically added to the global environment of the hscript instance you want to execute.

However, I feel there should be a better way to do this, or make it inbuilt. 

My knowledge of the hscript interpreter is limited, but I am open to suggestions on a better "in-built" way of achieving this.

Suggested syntax:

```hx
import HEX, RGB, CYMK from "Colors" 

export module View {
    
    function update(dt){
       display.color(HEX.RED);
    }

}
```

Modules could generally behave like Abstracts at runtime, can be subclassed and exported.

**Comment by ncannasse** [comment]
HScript follows Haxe syntax so we don't really want to add another specific syntax on top of it.
You can however use Haxe syntax for class/import/etc by using `parseModule` , however there is no way to "evaluate" a module atm, only expressions.

**Comment by darmie** [comment]
Okay, thank you

**Comment by ncannasse** [comment]
You're welcome
