### ISSUE TITLE
Haxe 4.0.0 has warning

### ISSUE THREAD

**Issue by manjav** [HaxeFoundation/hscript#82]
The definition Null depended on by hscript.Interp in the SWC could not be found
The definition Null depended on by haxe.ds.StringMap in the SWC could not be found
The definition Null depended on by flash.Boot in the SWC could not be found
The definition Null depended on by haxe.io.BytesInput in the SWC could not be found
The definition Null depended on by haxe.io.Bytes in the SWC could not be found
The definition Null depended on by com.gerantech.mmory.core.events.BattleEvent in the SWC could not be found
The definition Null depended on by hscript.CType in the SWC could not be found
The definition Null depended on by com.gerantech.mmory.core.utils.maps.IntIntMap in the SWC could not be found
The definition Null depended on by haxe.ds.BalancedTree in the SWC could not be found
The definition Null depended on by haxe.ds.ObjectMap in the SWC could not be found
The definition Null depended on by hscript.Expr in the SWC could not be found
The definition Null depended on by hscript.ModuleDecl in the SWC could not be found
The definition Null depended on by haxe.ds.IntMap in the SWC could not be found
The definition Null depended on by hscript.FieldKind in the SWC could not be found
The definition Null depended on by haxe.io.Input in the SWC could not be found
The definition Null depended on by haxe.ds.GenericStack_hscript_Token in the SWC could not be found
The definition Null depended on by hscript.Parser in the SWC could not be found
The definition Null depended on by haxe.Log in the SWC could not be found
The definition Null depended on by com.gerantech.mmory.core.battle.tilemap.TileMap in the SWC could not be found
The definition Null depended on by Std in the SWC could not be found
The definition Null depended on by haxe.IMap in the SWC could not be found

**Comment by ncannasse** [comment]
ping @nadako ?

**Comment by nadako** [comment]
https://github.com/HaxeFoundation/haxe/issues/7994?

**Comment by manjav** [comment]
Exactly.😋😁
Thanks.
