### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by maxless** [HaxeFoundation/hscript#87]
Is it currently possible to do something to make the interpreter ignore "cast" keyword in something like this? :
```
  var obj = { field: 3 };
  var a: Int = cast obj.field;
```

**Comment by ncannasse** [comment]
`Cast` expression is currently not supported by hscript, it would require adding it to Parser and ignore it in Interp.

**Comment by maxless** [comment]
Okay, thanks. Maybe I'll get to it.
