### ISSUE TITLE
Order of Operations Bug/Regression

### ISSUE THREAD

**Issue by Cleod9** [HaxeFoundation/hscript#94]
There is some type of order of operations bug recently introduced to hscript on the `master` branch. It causes mathematical order of operations to be incorrect in expressions that utilize arrays for storing objects. For example:

Let `list[0].getValue()` = `10`
Let  `b = 5`
**Expression:** `list[0].getValue() - b / 2`
**Expected value:** `7.5`
**Interpreted value:** `2.5`

Here's some usable source code demonstrating the issue:
https://github.com/Cleod9/hscript-ooo-bug

Note that this bug doesn't seem to affect `2.4.0` of hscript, it's just a newly introduced bug in master.

**Comment by ncannasse** [comment]
Wow thanks for reporting, I'm surprised it went unnoticed for 2 1/2 months :)
