### ISSUE TITLE
Recent features documentation

### ISSUE THREAD

**Issue by kiroukou** [HaxeFoundation/hscript#95]
Hello,
While hscript a really a fantastic lib, I've the feeling to not be able to get full of its power due to some missing documentation.

At leat, some samples would be greatly appreciated to get a better understanding the the use of features like : 
 - hscript.Checker
 - hscript.Async
 ..

hscriptPos error catching (synthax, or runtime) would be perfect as well for many newcomers to haxe.

With some quicks inputs of you, I'll be able to contribute to some samples/tutorials.

Best !

**Comment by ncannasse** [comment]
hscript.Async is well documented (see https://github.com/HaxeFoundation/hscript/blob/master/hscript/Async.hx#L51) but I agree some actual tutorial would be helpful.
Maybe you should just come visit us at Shiro for a quick workshop then you'll be ready to contribute the tutorials ;)

**Comment by kiroukou** [comment]
Agree for Async.   That was a more general feedback from feeling I get back when I ask teamate to work on hscript based tool, didn't made much investigation myself yet.

But yes, thanks for the offer, a visit/workshop session would be appreciated for many different aspects !  Let me come back to you with a date.
Cheers,
