### ISSUE TITLE
convert Expr -> Expr in the opposite direction

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/hscript#97]
I see that you can turn an Hscript Expr into a Macro Expr, but what about the other way around?

https://github.com/HaxeFoundation/hscript/blob/master/hscript/Macro.hx#L147

**Comment by ncannasse** [comment]
Yes, it's `hscript.Macro.convert(hscriptExpr)`

**Comment by NQNStudios** [comment]
No, I mean I'm looking for convertBack(haxe.macro.Expr): hscriptExpr

**Comment by ncannasse** [comment]
I don't think I have done this yet :)
